### PR TITLE
Lowercase letters for packagist

### PR DESCRIPTION
**Pull request by DrewAPicture**

### CODE REVIEW

**Comment by atimmer** [comment]
Did you register the package again with packagist? I think when the package name changes you have to register is again. And Ryan has to mark his package as replaced by this one.

**Comment by DrewAPicture** [comment]
> Ryan has to mark his package as replaced by this one

To my knowledge, there's no official way to "mark a package" as replaced, short of adding a `replace` clause to composer.json. And since @rmccue's package points to a redirected repo, *we'd* need to add the `replace` clause. He will need to update the repository URL in his package, however.

> Did you register the package again with packagist?

This part is complicated. We have to have the new package name in place in the composer.json file for Packagist to find. If it's the old name, it won't allow the new registration.

The current roadblock for submission is that the author of WordPress.Skeleton, @qckanemoto, has registered an unofficial package under the `wordpress` vendor namespace. I politely reached out to him on Twitter last night and explained the problem.
 
We'll probably ask him to transfer ownership of the `wordpress` vendor namespace eventually, but in the short term he should be able to register the new package and add the maintainers I asked for.

**Comment by atimmer** [comment]
Ryan can mark his package as "abandoned": https://github.com/composer/packagist/pull/421

Any maintainer of a package in a vendor can add new packages: https://github.com/composer/packagist/issues/163#issuecomment-99673878. So once the parser is added by @qckanemoto, other WordPress composer packages can be added without his involvement.

**Comment by DrewAPicture** [comment]
Yeah, what a terrible verb to use. They're basically doubling up on the "abandon" feature so they don't have to call it "rename". Either way, the crux of the issue is that to add the new package we have to temporarily break the old package because Packagist relies on the package name specified in composer.json.

**Comment by qckanemoto** [comment]
Sorry for my late action. I submitted wordpress/phpdoc-parser onto packagist and add "DrewAPicture" and "WordPress" as maintainers and removed me from maintainers.

**Comment by rmccue** [comment]
OK, just to double confirm: you want me to hit the big scary Abandon button on https://packagist.org/packages/rmccue/wp-parser and mark https://packagist.org/packages/wordpress/phpdoc-parser as the replacement?

**Comment by DrewAPicture** [comment]
@rmccue Yep :)

**Comment by rmccue** [comment]
Done!

**Pull request merged**
